### ISSUE TITLE
Add icons and favicon

### ISSUE THREAD

**Issue by DesignrKnight** [opencodenitr/project-apollo#8] opened 2020-09-27 11:20 UTC
Guide: https://www.favicon-generator.org/
Logo: https://drive.google.com/drive/folders/1u7Wz4lPOiG7u4aRxp5MAgi46F8vob0UM?usp=sharing

**Comment by HarishTeens** [comment] 2020-09-27 12:59
Hey @DesignrKnight , I am really to take up the issue, can you help me ?

**Comment by DesignrKnight** [comment] 2020-09-27 12:59
yeah, sure
You can take the issue. Tell me how I can help

**Comment by HarishTeens** [comment] 2020-09-27 13:00
Can you please assign me to this issue

**Comment by HARSHBHUDOLIA** [comment] 2020-09-27 13:01
What icon do you want me to generate?

**Comment by DesignrKnight** [comment] 2020-09-28 06:25
Issue up for grabs

**Comment by KoushikSahu** [comment] 2020-09-28 06:51
I am interested to resolve this issue. From what I understand I need to convert the logos to .ico and then make a folder named "Assets" maybe and have the icons in that folder. If I am correct please assign the issue to me.

**Comment by DesignrKnight** [comment] 2020-09-28 07:24
@riteshsp2000 @nayakashutosh9 
Suggest how it is to be done

**Comment by DesignrKnight** [comment] 2020-09-28 07:24
Assigned to you

**Comment by KoushikSahu** [comment] 2020-09-28 07:42
Thanks for assigning. I will be in touch with @nayakashutosh9 and will make a PR asap.

**Comment by KoushikSahu** [comment] 2020-09-29 02:52
There is already a favicon named opencode.png in the public/img directory which is the same as logo_black in the google drive link mentioned in the issue.

**Comment by DesignrKnight** [comment] 2020-09-29 04:41
That is just one logo and it is not the ideal size, create logos of all sizes and put there. We will use as per need

**Comment by KoushikSahu** [comment] 2020-09-29 05:44
Generating favicon from this website with dimension preserved adds unexpected whitespace at the bottom of the picture. Result of watermark_black with favicon-generator.org
![favicon-96x96](https://user-images.githubusercontent.com/39738439/94516807-4abf1300-0244-11eb-9cc2-243442c0a995.png)
(It may not be visible on white background of github. Please right click on the image and open in new tab)
If we uncheck the option to preserve dimension then it crops off the image from left and right
Should I go for some other website?

**Comment by ampsteric** [comment] 2020-09-29 05:49
I would like to work on this issue as well. please assign in case the issue is not resolved.

**Comment by DesignrKnight** [comment] 2020-09-29 06:42
> Generating favicon from this website with dimension preserved adds unexpected whitespace at the bottom of the picture. Result of watermark_black with favicon-generator.org
> ![favicon-96x96](https://user-images.githubusercontent.com/39738439/94516807-4abf1300-0244-11eb-9cc2-243442c0a995.png)
> (It may not be visible on white background of github. Please right click on the image and open in new tab)
> If we uncheck the option to preserve dimension then it crops off the image from left and right
> Should I go for some other website?

It worked fine for me last time I used. Also, just do for the OpenCode new logo and not the old one.

**Comment by DesignrKnight** [comment] 2020-09-29 06:43
> I would like to work on this issue as well. please assign in case the issue is not resolved.

Thank you for your interest to work on this, this is already assigned. We will be having more issues added soon. Looking forward to your contribution.

**Comment by KoushikSahu** [comment] 2020-09-29 06:47
> > Generating favicon from this website with dimension preserved adds unexpected whitespace at the bottom of the picture. Result of watermark_black with favicon-generator.org
> > ![favicon-96x96](https://user-images.githubusercontent.com/39738439/94516807-4abf1300-0244-11eb-9cc2-243442c0a995.png)
> > (It may not be visible on white background of github. Please right click on the image and open in new tab)
> > If we uncheck the option to preserve dimension then it crops off the image from left and right
> > Should I go for some other website?
> 
> It worked fine for me last time I used. Also, just do for the OpenCode new logo and not the old one.

@DesignrKnight Same unexpected whitespace at bottom for the new logo:
![favicon-96x96](https://user-images.githubusercontent.com/39738439/94522632-91653b00-024d-11eb-9146-7e7016e3223e.png)
(Please right click and open in new tab)

**Comment by DesignrKnight** [comment] 2020-09-29 07:04
![Group 1](https://user-images.githubusercontent.com/27865704/94524320-17828100-0250-11eb-9c73-bcfc848a1a5e.png)
Use this. I tried. It works

**Comment by KoushikSahu** [comment] 2020-09-29 09:55
@DesignrKnight Made a PR. Please review it.

**Comment by DesignrKnight** [comment] 2020-09-29 10:04
@nayakashutosh9 
Over to you

**Comment by DesignrKnight** [comment] 2020-09-29 10:08
@all-contributors add @KoushikSahu for code

**Closed as completed** 2020-09-29 10:24 UTC
Labels: good first issue, hacktoberfest, hacktoberfest2020, hacktoberfest-nitr, beginner
